"""
Django settings for ricenutrition project.

Generated by 'django-admin startproject' using Django 2.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '2h9m(1mqwoy1h37-#qd&6^yj%wk8e!cf^%dhxgz^@q(fv&r$fq'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',

    'profiles',
    'rice',

    'allauth',
    'allauth.account',
    'allauth.socialaccount',
]

SITE_ID = 1

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'ricenutrition.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, "templates")],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

AUTHENTICATION_BACKENDS = [
    # Needed to login by username in Django admin, regardless of `allauth`
    'django.contrib.auth.backends.ModelBackend',

    # `allauth` specific authentication methods, such as login by e-mail
    'allauth.account.auth_backends.AuthenticationBackend',
]

AUTH_USER_MODEL = 'profiles.User'

ACCOUNT_ADAPTER = 'profiles.adapter.RestrictEmailAdapter'

ACCOUNT_FORMS = {'signup': 'profiles.forms.CoreSignupForm'}

ACCOUNT_EMAIL_CONFIRMATION_HMAC=False

WSGI_APPLICATION = 'ricenutrition.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}

# MongoDB
HOST_MONGODB = 'mongodb://localhost:27017'
DB_NAME = 'riceNutrition'
COLLECTION_NAME = 'test'
COLLECTION_NAME_META = 'metaData'

# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Bangkok'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

STATIC_URL = '/static/'

STATICFILES_DIRS = [
    os.path.join(str(BASE_DIR),"static"),
    os.path.join(str(BASE_DIR),"rice/static"),
]

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(str(BASE_DIR),"media")

LOGIN_REDIRECT_URL = '/'


ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_AUTHENTICATION_METHOD = 'username_email'
ACCOUNT_EMAIL_VERIFICATION = 'mandatory'

if DEBUG:
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

# Email protocol

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_HOST_USER = 'test101auth@gmail.com'
EMAIL_HOST_PASSWORD = 'lfnlkovpvxmpirdr'
EMAIL_USE_TLS = True


FIRST_ROW_SAMPLE = ['cropSampleID', 'riceVarietiesTH', 'riceVarietiesEN', 'varietiesApprovedByRD', 'cropSiteProvince', 'cropSiteDistrict',
'cropSiteSubdistrict', 'cropSiteOtherInfo', 'yearOfProduction', 'seasonOfProduction', 'organicProduction', 'cropSeedSource', 'cropData',
'yearOfAnalysis', 'siteOfAnalysis', 'dataSource']
FIRST_ROW_BIO = ['nutritionDBID', 'cropSampleID', 'ferulicAcid', 'totalTocopherol', 'tocopherolAlpha', 'tocopherolBeta', 'tocopherolGamma',
'tocopherolDelta', 'tocotrienolAlpha', 'tocotrienolBeta', 'tocotrienolGamma', 'tocotrienolDelta', 'prolamine', 'albumin', 'globulin',
'glutenin', 'omega3', 'omega6', 'omega9', 'tryptophan', 'threonine', 'isoleucine','leucine', 'lysine', 'methionine', 'custeine',
'phenylalanine', 'tyrosine', 'valine', 'arginine', 'histidine', 'alanine', 'asparticAcid', 'glutamicAcid', 'glycine', 'proline', 'serine',
'cerine', 'caffeine', 'theobromine', 'beta-Carotene', 'alpha-Carotene', 'betaCryptoxanthin', 'lycopene', 'lutein&Zeaxanthin', 'biotin',
'gammaOryzanol', 'phenolicCompounds', 'totalAntioxidant', 'gallicAcid', 'eriodictyol', 'anthocyanin', 'apigenin', 'isoquercetin',
'hydroquinin', 'quercetin', 'Kaempferol', 'rutin', 'catechin', 'tannicAcid', 'totalFlavonoid', 'GABA', 'genistein', 'daidzein',
'genistin', 'daidzin', 'quercitin-3-B-D-glucoside', 'peonidin-3-O-glucoside', 'oenin', 'anthocyanin-3-glucoside', 'callistephin', 'keracyanin',
'kuromanin', 'malvidin-3-galactoside']
FIRST_ROW_CHEM = ['nutritionDBID', 'cropSampleID', 'amylose', 'solubleAmyloseContent', 'amylopectin',
'alkaliSpreading', 'water/moisture', 'aromaBySensory', 'content2AP', 'RAG', 'SAG', 'TG', 'ash']
FIRST_ROW_NUTRI = ['nutritionDBID', 'cropSampleID', 'totalEnergy', 'carbohydrate', 'starch', 'dietaryFiber', 'crudeFiber',
'totalSugar', 'protein', 'totalFat', 'saturatedFat', 'unsaturatedFat', 'saturatedFattyAcid', 'monosaturatedFattyAcid',
'polysaturatedFattyAcid', 'cholesterol', 'energyFromFat', 'calcium', 'iron', 'magnesium', 'phosphorus', 'potassium', 'sodium',
'zinc', 'iodine', 'copper', 'maganese', 'selenium', 'aluminium', 'vitaminA', 'betaCarotene', 'vitaminC', 'thiamine', 'pantothenicAcid',
'vitaminB1', 'vitaminB2', 'riboflavin', 'vitaminB3', 'vitaminB4', 'vitaminB5', 'vitaminB6', 'allFolate', 'folicAcid', 'foodFolate',
'DFEFolate', 'vitaminB12', 'retinol', 'vitaminE', 'vitaminK']
FIRST_ROW_PHY = ['nutritionDBID', 'cropSampleID', 'riceCategories', 'seedWeight', 'length', 'width', 'thickness', 'color', 'seedShapeRatio', 'chalkiness',
'gloss', 'whiteness', 'transparency', 'moisture', 'elongationRatio', 'swelling', 'texture', 'peakViscosity', 'trough', 'breakdown',
'finalViscosity', 'setback', 'pastingTemp', 'gelatinizationTemp', 'riceFlourViscosity', 'precipitation', 'retrogradation', 'gelation',
'gelConsistency', 'swellingPower', 'hardness', 'adhesiveness', 'stickiness']
